// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ-EvwMs6TCP9zHyyr1CjfZTdoMBa_pE4',
    appId: '1:618234153079:web:cde781cfdff07c30db5e72',
    messagingSenderId: '618234153079',
    projectId: 'yuvaraj-dekhane',
    authDomain: 'yuvaraj-dekhane.firebaseapp.com',
    storageBucket: 'yuvaraj-dekhane.firebasestorage.app',
    measurementId: 'G-PFVRZSDV7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjjCyglop7wFxWIqACoB7mLf0bAUGsZ0',
    appId: '1:618234153079:android:f5b6c29f301c6386db5e72',
    messagingSenderId: '618234153079',
    projectId: 'yuvaraj-dekhane',
    storageBucket: 'yuvaraj-dekhane.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FMHGahNmfew5vw9E7s6fwBT1CIipRF4',
    appId: '1:618234153079:ios:f173b78303fff79bdb5e72',
    messagingSenderId: '618234153079',
    projectId: 'yuvaraj-dekhane',
    storageBucket: 'yuvaraj-dekhane.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FMHGahNmfew5vw9E7s6fwBT1CIipRF4',
    appId: '1:618234153079:ios:f173b78303fff79bdb5e72',
    messagingSenderId: '618234153079',
    projectId: 'yuvaraj-dekhane',
    storageBucket: 'yuvaraj-dekhane.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ-EvwMs6TCP9zHyyr1CjfZTdoMBa_pE4',
    appId: '1:618234153079:web:527bb672ed62b7ecdb5e72',
    messagingSenderId: '618234153079',
    projectId: 'yuvaraj-dekhane',
    authDomain: 'yuvaraj-dekhane.firebaseapp.com',
    storageBucket: 'yuvaraj-dekhane.firebasestorage.app',
    measurementId: 'G-5R126CJJ10',
  );
}
